export const APPLY_MODAL = "APPLY_MODAL";
export const EDIT_MODAL = "EDIT_MODAL";
export const DELETE_MODAL = "DELETE_MODAL";
export const GET_FILMS_BY_RATING = "GET_FILMS_BY_RATING";
export const GET_FILMS_BY_RELEASE_DATE = "GET_FILMS_BY_RELEASE_DATE";
export const GET_FILMS_BY_GENRES = "GET_FILMS_BY_GENRES";
export const SET_FILTER = "SET_FILTER";
